executable              = ../../../impact.sh
arguments               = $(dir)
Initialdir              = $(dir)
						
output                  = run.out
error                   = run.err
log                     = run.log
						
RequestMemory           = 2000
ShouldTransferFiles     = NO
+JobFlavour             = "testmatch"
x509userproxy           = $ENV(HOME)/temp/x509up
Queue dir from ./condor_list.txt
