import ROOT as r
p2weight = 0.65 / 0.3
def cout():
    print(p2weight)
def format_leg(leg):
    leg.SetNColumns(1)
    leg.SetColumnSeparation(0.5)
    leg.SetEntrySeparation(0.0)
    leg.SetBorderSize(0)
    leg.SetTextFont(42)
    leg.SetTextSize(0.03)
    leg.SetLineColor(1)
    leg.SetLineStyle(1)
    leg.SetLineWidth(1)
    leg.SetFillColor(0)
    leg.SetFillStyle(0)
def format_canv(c):
    c.SetFillColor(0)
    c.SetBorderMode(0)
    c.SetBorderSize(2)
    c.SetTickx(1)
    c.SetTicky(1)
    c.SetLeftMargin(0.18)
    c.SetRightMargin(0.05)
    c.SetTopMargin(0.05)
    c.SetBottomMargin(0.15)
    c.SetFrameFillStyle(0)
    c.SetFrameBorderMode(0)
    c.SetFrameFillStyle(0)
    c.SetFrameBorderMode(0)
def format_stack(hstack, xtitle):
    hstack.GetXaxis().SetNdivisions(505)
    hstack.GetXaxis().SetLabelFont(42)
    hstack.GetXaxis().SetLabelOffset(0.007)
    hstack.GetXaxis().SetLabelSize(0.00)
    hstack.GetXaxis().SetTitleSize(0.04)
    hstack.GetXaxis().SetTitleOffset(1.3)
    hstack.GetXaxis().SetTitleFont(42)
    hstack.GetYaxis().SetNdivisions(505)
    hstack.GetYaxis().SetLabelFont(42)
    hstack.GetYaxis().SetLabelOffset(0.007)
    hstack.GetYaxis().SetLabelSize(0.05)
    hstack.GetYaxis().SetTitleSize(0.06)
    hstack.GetYaxis().SetTitleOffset(1.1)
    hstack.GetYaxis().SetTitleFont(42)
    hstack.GetXaxis().CenterTitle()
    hstack.GetYaxis().CenterTitle()
    hstack.GetXaxis().SetTitle("")
    hstack.GetYaxis().SetTitle("Events/bin")
    hstack.SetMaximum(hstack.GetMaximum() * 1.4)

def format_pad(pad1, pad2, pad3):
    pad1.Draw()
    pad2.Draw()
    pad3.Draw()
    pad1.cd()
    pad1.SetTopMargin(0.1)
    pad1.SetBottomMargin(0.02)
    pad1.SetLeftMargin(0.15)
    pad2.cd()
    pad2.SetTopMargin(0.03)
    pad2.SetBottomMargin(0.35)
    pad2.SetLeftMargin(0.15)
    if pad3 != None:
        pad3.cd()
        pad3.SetTopMargin(0.03)
        pad3.SetBottomMargin(0.35)
        pad3.SetLeftMargin(0.15)
        pad3.SetFillColor(0)
        pad3.SetFillStyle(4000)
        pad3.SetFrameFillStyle(0)

def format_tex(text):
    text.SetNDC()
    text.SetTextAngle(0)
    text.SetTextColor(r.kBlack)
    text.SetTextFont(42)
    text.SetTextAlign(31)
    text.SetTextSize(0.06)

def format_text(lumi, option):
    lumi.SetFillColor(0)
    lumi.SetTextFont(42)
    if option:
        lumi.SetTextColor(1)
        lumi.SetTextSize(0.045)
    else:
        lumi.SetTextSize(0.035)
        lumi.SetTextColor(r.kBlack)
    lumi.SetBorderSize(0)

def format_his(h1, xtitle, color, type):
    if type == 2:
        h1.SetMarkerStyle(1)
        h1.SetLineWidth(2)
        h1.SetLineColor(color)
        h1.SetStats(r.kFALSE)
        h1.GetXaxis().SetTitle(xtitle)
        h1.GetYaxis().SetTitle("Ratio")
        h1.SetTitle("")
        h1.GetXaxis().CenterTitle()
        h1.GetYaxis().CenterTitle()
        h1.GetYaxis().SetNdivisions(505)
        h1.GetXaxis().SetTitleSize(0.12)
        h1.GetYaxis().SetTitleSize(0.06 * p2weight)
        h1.GetXaxis().SetTitleOffset(3.8)
        h1.GetYaxis().SetTitleOffset(1.1 / p2weight)
        h1.GetXaxis().SetLabelSize(0.11)
        h1.GetYaxis().SetLabelSize(0.05 * p2weight)
        h1.GetYaxis().SetRangeUser(0.5, 1.5)
    elif type == 0:
        h1.SetMarkerSize(0.8)
        h1.SetMarkerStyle(21)
    else:
        h1.SetMarkerStyle(1)
        h1.SetLineWidth(2)
        h1.SetLineColor(color)
        h1.SetStats(r.kFALSE)
        h1.GetXaxis().SetTitle(xtitle)
        h1.GetYaxis().SetTitle("Events")
        h1.SetTitle("")
        h1.GetXaxis().CenterTitle()
        h1.GetYaxis().CenterTitle()
        h1.GetYaxis().SetNdivisions(505)
        h1.GetXaxis().SetTitleSize(0)
        h1.GetYaxis().SetTitleSize(0.07)
        h1.GetXaxis().SetTitleOffset(1.0)
        h1.GetYaxis().SetTitleOffset(1.1)
        h1.GetXaxis().SetLabelSize(0)
        h1.GetYaxis().SetLabelSize(0.05)
        h1.GetYaxis().SetRangeUser(0, h1.GetMaximum() * 1.3)

def format_line(l1, is_net = True):
    if is_net:
        l1.SetLineWidth(1)
        l1.SetLineStyle(3)
    else:
        l1.SetLineWidth(2)
        l1.SetLineStyle(9)
    l1.SetLineColor(1)

def format_graph(hg, color):
    r.gStyle.SetHatchesSpacing(0.65)
    r.gStyle.SetHatchesLineWidth(1) 
    hg.SetFillColor(color)
    hg.SetFillStyle(3353)